project_id = "pesysijvsvjfkjcjmoes"

[functions.chat]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-order-confirmation]
verify_jwt = false

[functions.generate-audiobook]
verify_jwt = false

[functions.extract-pdf-text]
verify_jwt = false
